[App]
Name = "ai.h2o.wave.h2o_wave_ml"
Version = "0.7.0"
Title = "H2O Wave ML"
Description = "Summary of H2O Wave ML capabilities and features"
LongDescription = "LongDescription.md"
Category = "Machine Learning"
Keywords = ["ai", "h2o", "ml", "wave"]

[Runtime]
Module = "src.app"
VolumeMount = "/data"
VolumeSize = "9Gi"
ResourceVolumeSize = "1Gi"
MemoryLimit = "9Gi"
MemoryReservation = "1Gi"
CPULimit = "4"
CPUReservation = "1"
GPUCount = 0
GPUType = ""
EnableOIDC = false