[App]
Name = "ai.h2o.wave.ml.quickstart"
Version = "0.0.1"
Title = "Confusion Matrix Quickstart"
Description = "App shows a WaveML used inside a cloud"
Category = "Other"
Keywords = ["waveml", "automl"]

[Runtime]
Module = "run"
EnableOIDC = true

[[Env]]
Name = "H2O_WAVE_ML_STEAM_INSTANCE_NAME"
Value = "my-dai"

[[Env]]
Name = "H2O_WAVE_ML_STEAM_VERIFY_SSL"
Value = "False"

[[Env]]
Name = "H2O_WAVE_ML_STEAM_ADDRESS"
Secret = "h2oai-steam"
SecretKey = "api"

[[Env]]
Name = "H2O_WAVE_ML_MLOPS_GATEWAY"
Secret = "h2oai-mlops"
SecretKey = "gateway"
