name: Check Pull Request
on: [pull_request]
jobs:
  qa:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Deps
        run: pip install flake8 mypy

      - name: Run flake8
        continue-on-error: true
        run: flake8 h2o_wave_ml --ignore=E501

      - name: Run mypy
        continue-on-error: true
        run: mypy --ignore-missing-imports h2o_wave_ml/*.py
