name: Release a New Version
on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/release-changelog-builder-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build package
        run: make release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}-testing
          release_name: v${{ env.VERSION }}-testing
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Package to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/h2o_wave_ml-${{ env.VERSION }}-py3-none-any.whl
          asset_name: h2o_wave_ml-${{ env.VERSION }}-py3-none-any.whl
          asset_content_type: application/x-pywheel+zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
