name: Snyk Security Vulnerability Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: snyk/actions/setup@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Snyk scan for Python dependencies
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          for file in $(find . -name "requirements.txt"); do
            python3 -m pip install -r $file
            snyk test --command=python3 --package-manager=pip --file=$file -d --skip-unresolved 
          done
  
  snyk_scan_monitor:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract github branch/tag name
        shell: bash
        run: echo "ref=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_ref
      
      - uses: actions/checkout@master

      - uses: snyk/actions/setup@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Snyk scan for Python dependencies - requirements.txt files
        continue-on-error: true
        run: |
          for file in $(find . -name "requirements.txt"); do
            python3 -m pip install -r $file
            file=${file:2}
            snyk monitor --command=python3 --package-manager=pip --org=h2o-3-automl --remote-repo-url=wave-ml/${{ steps.extract_ref.outputs.ref }} --file=$file --project-name=H2O-3-AUTOML/wave-ml/${{ steps.extract_ref.outputs.ref }}/$file -d --skip-unresolved 
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
